# Generated by Django 3.1.6 on 2021-02-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210214_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='id',
        ),
        migrations.AddField(
            model_name='balance',
            name='name',
            field=models.CharField(default='(Payer.name, User.name)', help_text='Balance key: (Payer.name, User.name)', max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
