# Generated by Django 3.1.6 on 2021-02-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210217_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balance',
            name='key',
            field=models.CharField(default='(Payer.name, User.name)', help_text='Balance key: (Payer.name, User.name)', max_length=200, unique=True),
        ),
    ]
