# Generated by Django 3.1.6 on 2021-02-15 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210215_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='name',
            new_name='key',
        ),
    ]
