# Generated by Django 3.1.6 on 2021-02-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210217_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='id',
        ),
        migrations.AlterField(
            model_name='balance',
            name='key',
            field=models.CharField(default='(Payer.name, User.name)', help_text='Balance key: (Payer.name, User.name)', max_length=200, primary_key=True, serialize=False),
        ),
    ]
